/**
 * 💬 Entity: Comment
 *
 * Represents a user-submitted comment on an outfit.
 * Each comment is authored by a specific user and linked to a specific outfit.
 *
 * 🔹 Table Name: `comments`
 *
 * 🔹 Purpose:
 * - Store textual feedback and discussions related to outfits.
 * - Maintain referential integrity between users and outfits.
 *
 * 🔹 Relationships:
 * - Many-to-One → `User`: The author who wrote the comment.
 * - Many-to-One → `Outfit`: The outfit that the comment belongs to.
 *
 * 🔹 Cascade Behavior:
 * - If a user or outfit is deleted, their associated comments are automatically removed.
 *
 * 🔹 Columns Summary:
 * | Column        | Type                     | Description                            |
 * |----------------|--------------------------|----------------------------------------|
 * | comment_id     | integer (PK)             | Unique identifier for the comment.     |
 * | comment_text   | text                     | The actual message written by the user.|
 * | created_at     | timestamp with time zone | When the comment was posted.           |
 * | user_id (FK)   | integer                  | References the author (User entity).   |
 * | outfit_id (FK) | integer                  | References the related outfit.         |
 *
 * 🔹 Preconditions:
 * - Both `User` and `Outfit` must exist before a comment can be created.
 *
 * 🔹 Postconditions:
 * - Comment is stored in the database and linked to both entities.
 */

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  CreateDateColumn,
  JoinColumn,
} from 'typeorm';
import { User } from '../user/user.entity';
import { Outfit } from '../outfit/outfit.entity';

@Entity('comments')
export class Comment {
  /**
   * 🔑 Primary Key — Unique identifier for each comment.
   * Auto-incremented integer value.
   * @example 42
   */
  @PrimaryGeneratedColumn()
  comment_id: number;

  /**
   * 💬 Textual content of the comment.
   * Cannot be empty or null.
   * @example "I love this outfit, especially the color combination!"
   */
  @Column({ type: 'text', name: 'comment_text', nullable: false })
  comment_text: string;

  /**
   * 🕒 Timestamp marking when the comment was created.
   * Automatically generated by the database.
   */
  @CreateDateColumn({ name: 'created_at', type: 'timestamp with time zone' })
  created_at: Date;

  // ----------- RELATIONS -----------

  /**
   * 👤 Many-to-One relationship linking the comment to its author.
   * Each comment belongs to one user.
   * If the user is deleted, their comments are also deleted.
   */
  @ManyToOne(() => User, (user) => user.comments, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'user_id' })
  user: User;

  /**
   * 👗 Many-to-One relationship linking the comment to the outfit it refers to.
   * Each comment belongs to one outfit.
   * If the outfit is deleted, its comments are removed.
   */
  @ManyToOne(() => Outfit, (outfit) => outfit.comments, {
    onDelete: 'CASCADE',
    nullable: false,
  })
  @JoinColumn({ name: 'outfit_id' })
  outfit: Outfit;
}
