import type { CSSProperties } from "react";

export const creatorProfileStyles: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    padding: "48px 0 72px",
    background: "linear-gradient(135deg, #f8bbd0 0%, #b39ddb 100%)",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
  },
  inner: {
    maxWidth: "1080px",
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    flexDirection: "column",
    gap: "28px",
  },
  navHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: "rgba(255,255,255,0.9)",
    borderRadius: "24px",
    padding: "16px 24px",
    boxShadow: "0 20px 50px rgba(31,24,53,0.16)",
    position: "sticky",
    top: "24px",
    zIndex: 10,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    flexWrap: "wrap",
  },
  brand: {
    textDecoration: "none",
    color: "#1f1f2b",
    fontWeight: 700,
    fontSize: "1.2rem",
    letterSpacing: "0.04em",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "0.95rem",
  },
  navLink: {
    color: "#c2185b",
    textDecoration: "none",
    fontWeight: 600,
    padding: "8px 18px",
    borderRadius: "999px",
    background: "rgba(236,64,122,0.12)",
    border: "1px solid rgba(236,64,122,0.25)",
    transition: "background 0.2s ease, color 0.2s ease, transform 0.18s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  navLinkActive: {
    color: "white",
    background: "#ec407a",
    borderColor: "rgba(236,64,122,0.4)",
    boxShadow: "0 12px 26px rgba(236,64,122,0.25)",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  navProfileWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "rgba(255,255,255,0.85)",
    padding: "6px 12px",
    borderRadius: "999px",
    boxShadow: "0 12px 24px rgba(31,24,53,0.12)",
  },
  navProfileButton: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  navProfileAvatar: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    background: "#ec407a",
    color: "white",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    overflow: "hidden",
  },
  navProfileAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  navLogoutButton: {
    border: "none",
    background: "#ff7775",
    color: "white",
    borderRadius: "999px",
    padding: "6px 12px",
    fontSize: "0.85rem",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 6px 12px rgba(255,119,117,0.3)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backLink: {
    color: "#ec407a",
    fontWeight: 600,
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  },
  hero: {
    background: "rgba(255,255,255,0.92)",
    borderRadius: "30px",
    padding: "32px",
    boxShadow: "0 30px 60px rgba(31,24,53,0.18)",
    display: "flex",
    flexDirection: "column",
    gap: "22px",
  },
  heroTopRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "24px",
    alignItems: "center",
  },
  avatar: {
    width: "96px",
    height: "96px",
    borderRadius: "26px",
    background: "linear-gradient(135deg, #f48fb1, #ce93d8)",
    color: "white",
    fontSize: "2rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    letterSpacing: "0.1em",
  },
  heroText: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  heroName: {
    margin: 0,
    fontSize: "2rem",
    color: "#2f2f3a",
  },
  heroHandle: {
    margin: 0,
    fontSize: "1rem",
    color: "#6b6879",
  },
  statsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "18px",
    marginTop: "10px",
  },
  statCard: {
    background: "rgba(236,64,122,0.1)",
    color: "#d81b60",
    padding: "14px 18px",
    borderRadius: "18px",
    fontWeight: 600,
    display: "flex",
    flexDirection: "column",
    minWidth: "140px",
  },
  statLabel: {
    fontSize: "0.85rem",
    opacity: 0.8,
  },
  statValue: {
    fontSize: "1.4rem",
  },
  section: {
    background: "rgba(255,255,255,0.9)",
    borderRadius: "28px",
    padding: "28px",
    boxShadow: "0 24px 50px rgba(31,24,53,0.16)",
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  sectionTitle: {
    margin: 0,
    fontSize: "1.5rem",
    color: "#2f2f3a",
  },
  outfitGrid: {
    display: "grid",
    gap: "22px",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
  },
  outfitCard: {
    borderRadius: "22px",
    overflow: "hidden",
    background: "rgba(251, 233, 244, 0.65)",
    boxShadow: "0 16px 36px rgba(31,24,53,0.14)",
    display: "flex",
    flexDirection: "column",
  },
  outfitCover: {
    width: "100%",
    aspectRatio: "4 / 5",
    objectFit: "cover",
    background: "rgba(255,255,255,0.65)",
  },
  outfitBody: {
    padding: "18px",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  outfitName: {
    margin: 0,
    fontWeight: 600,
    color: "#2f2f3a",
    fontSize: "1.05rem",
  },
  outfitMeta: {
    margin: 0,
    color: "#6b6879",
    fontSize: "0.85rem",
  },
  wardrobeStrip: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
  },
  wardrobeCard: {
    borderRadius: "18px",
    background: "rgba(251, 233, 244, 0.55)",
    padding: "14px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    boxShadow: "0 12px 24px rgba(31,24,53,0.12)",
  },
  wardrobeImageShell: {
    borderRadius: "14px",
    overflow: "hidden",
    height: "140px",
    background: "rgba(255,255,255,0.65)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  wardrobeImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  wardrobeFallback: {
    fontWeight: 700,
    color: "#d81b60",
    fontSize: "1.1rem",
  },
  wardrobeName: {
    margin: 0,
    fontWeight: 600,
    color: "#322f3d",
  },
  wardrobeMeta: {
    margin: 0,
    color: "#7a7785",
    fontSize: "0.85rem",
  },
  divider: {
    height: "1px",
    background: "rgba(31,24,53,0.08)",
    margin: "12px 0",
  },
  loading: {
    textAlign: "center",
    color: "#5b5b66",
    fontWeight: 600,
    padding: "120px 0",
    fontSize: "1.1rem",
  },
  errorBox: {
    background: "rgba(244, 67, 54, 0.15)",
    color: "#c62828",
    borderRadius: "18px",
    padding: "20px",
    fontWeight: 600,
    textAlign: "center",
    boxShadow: "0 18px 40px rgba(31,24,53,0.12)",
  },
  emptyState: {
    color: "#6b6879",
    fontSize: "0.95rem",
    fontWeight: 500,
    background: "rgba(255,255,255,0.8)",
    padding: "28px",
    borderRadius: "20px",
    textAlign: "center",
  },
}
