import type { CSSProperties } from "react";

export const feedStyles: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    padding: "48px 0 64px",
    background: "linear-gradient(135deg, #f8bbd0 0%, #fbe9e7 100%)",
    boxSizing: "border-box",
    fontFamily: "'Poppins', sans-serif",
  },
  inner: {
    maxWidth: "1120px",
    margin: "0 auto",
    padding: "0 24px",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "36px",
    background: "rgba(255,255,255,0.95)",
    borderRadius: "22px",
    padding: "18px 26px",
    boxShadow: "0 20px 44px rgba(31,24,53,0.12)",
    position: "sticky",
    top: "18px",
    zIndex: 5,
    backdropFilter: "blur(16px)",
    gap: "18px",
    flexWrap: "wrap",
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "18px",
    flexWrap: "wrap",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  brand: {
    textDecoration: "none",
    color: "#1f1f2b",
    fontWeight: 700,
    fontSize: "1.32rem",
    letterSpacing: "0.04em",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    fontSize: "0.95rem",
  },
  navLink: {
    color: "#c2185b",
    textDecoration: "none",
    fontWeight: 600,
    padding: "8px 18px",
    borderRadius: "999px",
    background: "rgba(236,64,122,0.12)",
    border: "1px solid rgba(236,64,122,0.25)",
    transition: "background 0.2s ease, color 0.2s ease, transform 0.18s ease",
    boxShadow: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    position: "relative",
  },
  navLinkActive: {
    color: "white",
    background: "#ec407a",
    borderColor: "rgba(236,64,122,0.4)",
    boxShadow: "0 12px 26px rgba(236,64,122,0.25)",
  },
  profileWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    background: "rgba(255,255,255,0.85)",
    padding: "8px 14px",
    borderRadius: "999px",
    boxShadow: "0 12px 24px rgba(31,24,53,0.12)",
  },
  profileSummaryButton: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  profileAvatar: {
    width: "38px",
    height: "38px",
    borderRadius: "50%",
    background: "#ec407a",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    overflow: "hidden",
    border: "2px solid rgba(255,255,255,0.9)",
  },
  profileAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  logoutButton: {
    border: "none",
    background: "#ff7775",
    color: "white",
    borderRadius: "999px",
    padding: "8px 14px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 10px 20px rgba(255,119,117,0.32)",
  },
  hero: {
    background: "rgba(255,255,255,0.94)",
    borderRadius: "28px",
    padding: "36px",
    boxShadow: "0 30px 70px rgba(31,24,53,0.18)",
    marginBottom: "40px",
  },
  heroTitle: {
    margin: 0,
    fontSize: "2.3rem",
    color: "#2f2f3a",
    letterSpacing: "0.03em",
  },
  heroBody: {
    margin: "14px 0 26px",
    color: "#5b5b66",
    fontSize: "1.02rem",
    lineHeight: 1.6,
    maxWidth: "620px",
  },
  searchForm: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "12px",
  },
  searchInput: {
    flex: 1,
    minWidth: "220px",
    borderRadius: "999px",
    padding: "12px 20px",
    border: "none",
    background: "rgba(255,255,255,0.75)",
    fontSize: "1rem",
    color: "#2f2f3a",
    boxShadow: "0 12px 26px rgba(31,24,53,0.12)",
    outline: "none",
  },
  primaryButton: {
    border: "none",
    borderRadius: "999px",
    padding: "12px 26px",
    background: "#ec407a",
    color: "white",
    fontWeight: 600,
    fontSize: "1rem",
    cursor: "pointer",
    boxShadow: "0 16px 30px rgba(236,64,122,0.32)",
  },
  clearButton: {
    border: "none",
    background: "transparent",
    color: "#ec407a",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "0.95rem",
    textDecoration: "underline",
  },
  notice: {
    marginBottom: "24px",
    padding: "14px 20px",
    borderRadius: "14px",
    fontWeight: 600,
    boxShadow: "0 18px 40px rgba(31,24,53,0.12)",
  },
  errorBox: {
    marginBottom: "24px",
    padding: "18px 20px",
    borderRadius: "16px",
    color: "#c62828",
    fontWeight: 600,
    background: "rgba(244, 67, 54, 0.12)",
    boxShadow: "0 18px 40px rgba(31,24,53,0.12)",
  },
  loading: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "80px 0",
    color: "#5b5b66",
    fontSize: "1.1rem",
    fontWeight: 600,
  },
  emptyState: {
    background: "rgba(255,255,255,0.9)",
    borderRadius: "28px",
    padding: "48px 32px",
    textAlign: "center",
    boxShadow: "0 26px 60px rgba(31,24,53,0.16)",
    color: "#5b5b66",
    fontSize: "1.05rem",
    fontWeight: 500,
  },
  feedGrid: {
    display: "grid",
    gap: "56px 48px",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    justifyItems: "center",
    alignItems: "stretch",
    marginTop: "32px",
  },
  card: {
    background: "rgba(255,255,255,0.96)",
    borderRadius: "24px",
    padding: "20px 20px 24px",
    boxShadow: "0 18px 40px rgba(31,24,53,0.14)",
    border: "1px solid rgba(236,64,122,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    position: "relative",
    width: "100%",
    maxWidth: "320px",
    minHeight: "100%",
  },
  creatorRow: {
    display: "flex",
    alignItems: "center",
    gap: "14px",
    border: "none",
    background: "transparent",
    padding: 0,
    width: "100%",
    textAlign: "left",
    cursor: "pointer",
  },
  avatar: {
    width: "48px",
    height: "48px",
    borderRadius: "14px",
    color: "white",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.1rem",
    letterSpacing: "0.04em",
  },
  cover: {
    borderRadius: "20px",
    overflow: "hidden",
    minHeight: "220px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  coverImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  coverFallback: {
    color: "rgba(255,255,255,0.86)",
    fontWeight: 700,
    fontSize: "1.1rem",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    padding: "24px",
    textAlign: "center",
  },
  cardTitle: {
    margin: "0 0 10px",
    fontSize: "1.35rem",
    color: "#2f2f3a",
  },
  cardBody: {
    margin: 0,
    color: "#6b6879",
    fontSize: "0.95rem",
    lineHeight: 1.5,
  },
  actionRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "10px",
    flexWrap: "wrap",
    paddingTop: "6px",
  },
  actionButton: {
    flex: "0 0 auto",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    borderRadius: "999px",
    padding: "8px 16px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.9rem",
    boxShadow: "0 10px 20px rgba(31,24,53,0.12)",
    border: "1px solid transparent",
    background: "rgba(32,26,53,0.06)",
    color: "#322f3d",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  commentPanel: {
    borderRadius: "18px",
    background: "rgba(251, 233, 244, 0.55)",
    padding: "18px 18px 16px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
    boxShadow: "inset 0 12px 32px rgba(236,64,122,0.12)",
  },
  commentInput: {
    width: "100%",
    borderRadius: "14px",
    border: "1px solid rgba(236,64,122,0.25)",
    padding: "10px 14px",
    fontSize: "0.95rem",
    resize: "vertical",
    minHeight: "64px",
  },
  commentItem: {
    background: "rgba(255,255,255,0.9)",
    borderRadius: "14px",
    padding: "10px 14px",
    boxShadow: "0 8px 18px rgba(31,24,53,0.08)",
  },
  commentMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "6px",
    fontSize: "0.8rem",
    color: "#7a7785",
  },
  commentText: {
    margin: 0,
    color: "#4c475e",
    fontSize: "0.9rem",
    lineHeight: 1.4,
  },
  creatorSearchResults: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  creatorResultButton: {
    border: "1px solid rgba(236,64,122,0.22)",
    borderRadius: "999px",
    padding: "8px 14px",
    background: "rgba(255,255,255,0.85)",
    color: "#2f2f3a",
    display: "inline-flex",
    alignItems: "center",
    gap: "10px",
    cursor: "pointer",
    boxShadow: "0 12px 24px rgba(236,64,122,0.18)",
  },
  creatorResultName: {
    fontWeight: 600,
    fontSize: "0.95rem",
    margin: 0,
  },
  creatorResultHandle: {
    fontSize: "0.8rem",
    color: "#7a7785",
  },
  creatorSearchEmpty: {
    color: "#6b6879",
    fontSize: "0.9rem",
  },
}
