import type { CSSProperties } from "react";

export const homeStyles: Record<string, CSSProperties> = {
  pageContainer: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    background: "linear-gradient(135deg, #f8bbd0 0%, #fbe9e7 100%)",
    padding: "20px 5vw",
    boxSizing: "border-box",
    overflow: "hidden",
    fontFamily: "'Poppins', sans-serif",
  },
  weatherWrapper: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    marginBottom: "10px",
    padding: "10px 0",
  },
  contentLayout: {
    display: "flex",
    width: "100%",
    height: "calc(100% - 100px)",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "40px",
    position: "relative",
  },
  introCard: {
    flex: "0 0 45%",
    textAlign: "left",
    color: "#333",
    padding: "50px",
    borderRadius: "20px",
    backgroundColor: "rgba(255,255,255,0.75)",
    backdropFilter: "blur(10px)",
    boxShadow: "0 8px 20px rgba(0,0,0,0.1)",
    height: "fit-content",
    position: "relative",
    zIndex: 3,
  },
  title: {
    fontSize: "2.8rem",
    marginBottom: "10px",
  },
  titleEmoji: {
    marginLeft: "8px",
  },
  subtitle: {
    marginTop: 0,
  },
  description: {
    fontSize: "1.2rem",
    lineHeight: "1.6",
  },
  ctaRow: {
    marginTop: "30px",
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
  },
  primaryButton: {
    textDecoration: "none",
    background: "#ec407a",
    color: "white",
    padding: "12px 30px",
    borderRadius: "25px",
    fontWeight: "bold",
    boxShadow: "0 4px 8px rgba(0,0,0,0.2)",
  },
  sceneWrapper: {
    flex: "1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    zIndex: 3,
  },
  closetScene: {
    position: "relative",
    width: "500px",
    height: "500px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  backgroundFrame: {
    position: "absolute",
    width: "320px",
    height: "420px",
    backgroundImage: "url('/images/leopard.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "15px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.3)",
    border: "3px solid #8b4513",
  },
  carouselWrapper: {
    position: "relative",
    width: "420px",
    height: "300px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  statusText: {
    fontSize: "14px",
    textAlign: "center",
    color: "#666",
  },
  errorState: {
    textAlign: "center",
  },
  errorText: {
    fontSize: "14px",
    color: "#c62828",
    marginBottom: "12px",
  },
  retryButton: {
    background: "#ec407a",
    color: "white",
    border: "none",
    padding: "8px 16px",
    borderRadius: "18px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  carouselCard: {
    position: "absolute",
    background: "white",
    borderRadius: "16px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
  },
  carouselImage: {
    width: "100%",
    borderRadius: "10px",
    marginBottom: "12px",
    objectFit: "cover",
  },
  carouselImageFallback: {
    width: "100%",
    borderRadius: "10px",
    background: "linear-gradient(135deg, rgba(236,64,122,0.08), rgba(251,233,231,0.35))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "12px",
    color: "#8b4513",
    fontSize: "12px",
    fontWeight: 600,
  },
  loadingHint: {
    fontSize: "11px",
    color: "#888",
    marginBottom: "8px",
    textAlign: "center",
  },
  errorHint: {
    fontSize: "11px",
    color: "#c62828",
    marginBottom: "8px",
    textAlign: "center",
  },
  cardTitle: {
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "4px",
  },
  cardOwner: {
    fontSize: "11px",
    textAlign: "center",
    color: "#666",
    fontStyle: "italic",
  },
  emptyState: {
    fontSize: "14px",
    textAlign: "center",
    color: "#666",
    zIndex: 5,
  },
  counterBadge: {
    position: "absolute",
    bottom: "30px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "rgba(255,255,255,0.9)",
    padding: "6px 14px",
    borderRadius: "18px",
    fontSize: "11px",
    fontWeight: "bold",
    color: "#8b4513",
    boxShadow: "0 3px 12px rgba(0,0,0,0.1)",
    zIndex: 20,
  },
  sparkleBase: {
    position: "absolute",
    background: "rgba(255,255,255,0.95)",
    borderRadius: "50%",
    boxShadow: "0 4px 12px rgba(0,0,0,0.12)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ec407a",
    zIndex: 4,
    animation: "float 4s ease-in-out infinite",
  },
};
